name: Java CI with Maven

on:
  push:
    branches:
      - Developer
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    name: Build and Deploy on ${{ matrix.os }}

    steps:
      - name: Get Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Run Tests
        run: |
          mvn clean test -B \
          -Dstyle.color=always \
          -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn

      - name: Build with Maven
        run: |
          mvn clean package -B \
          -Dstyle.color=always \
          -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn

      - name: Create Release
        id: create_release
        if: github.ref == 'refs/heads/main'  # Only create a release on main branch
        uses: actions/create-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: v1.0.${{ github.run_number }}
          release_name: "Release v1.0.${{ github.run_number }}"
          draft: false
          prerelease: false

      - name: Upload Shaded JAR to Release
        if: success() && github.ref == 'refs/heads/main'  # Only upload on main branch success
        uses: actions/upload-release-asset@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: target/uml-editor-shaded.jar
          asset_name: uml-editor-shaded-${{ matrix.os }}.jar
          asset_content_type: application/java-archive
